export enum AccessScopesEnum {
    LOGGED_IN = 'LOGGED_IN',
    CAN_CREATE_STAFF = 'CAN_CREATE_STAFF',
    CAN_READ_STAFF = 'CAN_READ_STAFF',
    CAN_UPDATE_STAFF = 'CAN_UPDATE_STAFF',
    CAN_DELETE_STAFF = 'CAN_DELETE_STAFF',
    CAN_CREATE_JOURNALS = 'CAN_CREATE_JOURNALS',
    CAN_READ_JOURNALS = 'CAN_READ_JOURNALS',
    CAN_UPDATE_JOURNALS = 'CAN_UPDATE_JOURNALS',
    CAN_DELETE_JOURNALS = 'CAN_DELETE_JOURNALS',
}
